#!/usr/bin/python -tt
#
# livecd-creator : Creates Live CD based for Fedora.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import getopt
import os
import os.path
import sys
import tempfile
import time
import traceback
import subprocess
import shutil

from pykickstart.parser import *
from pykickstart.version import *

import yum

class BindChrootMount:
    """Represents a bind mount of a directory into a chroot."""
    def __init__(self, src, chroot, dest = None):
        self.src = src
        self.root = chroot
        if dest:
            self.dest = dest
        else:
            self.dest = src

        self.mounted = False

    def mount(self):
        if not self.mounted:
            if not os.path.exists("%s/%s" %(self.root, self.dest)):
                os.makedirs("%s/%s" %(self.root, self.dest))
            rc = subprocess.call(["/bin/mount", "--bind", self.src,
                                  "%s/%s" %(self.root, self.dest)])
            if rc == 0:
                self.mounted = True
        return self.mounted

    def umount(self):
        if self.mounted:
            rc = subprocess.call(["/bin/umount",
                                  "%s/%s" %(self.root, self.dest)])
            self.mounted = False
        

class LoopbackMount:
    def __init__(self, lofile, mountdir, fstype = None):
        self.lofile = lofile
        self.mountdir = mountdir
        self.fstype = fstype

        self.mounted = False
        self.losetup = False
        self.loopdev = None

    def cleanup(self, rmdir = True):
        self.umount()
        self.lounsetup()
        if rmdir:
            try:
                os.rmdir(self.mountdir)
            except OSError, e:
                pass

    def umount(self):
        if self.mounted:
            rc = subprocess.call(["/bin/umount", self.mountdir])
            self.mounted = False

    def lounsetup(self):
        if self.losetup and self.loopdev:
            rc = subprocess.call(["/sbin/losetup", "-d", self.loopdev])
            self.losetup = False
            self.loopdev = None

    def setup(self):
        if not os.path.exists(self.mountdir):
            os.makedirs(self.mountdir)
        if self.loopsetup():
            if self.mount():
                return True
        return False

    def loopsetup(self):
        if self.losetup:
            return self.losetup
        rc = subprocess.call(["/sbin/losetup", "-f", self.lofile])
        if rc != 0:
            return self.losetup

        # succeeded; figure out which loopdevice we're using
        buf = subprocess.Popen(["/sbin/losetup", "-a"],
                               stdout=subprocess.PIPE).communicate()[0]
        for line in buf.split("\n"):
            # loopdev: fdinfo (filename)
            fields = line.split()
            if len(fields) != 3:
                continue
            if fields[2] == "(%s)" %(self.lofile,):
                self.loopdev = fields[0][:-1]
                break

        if self.loopdev:
            self.losetup = True
        return self.losetup

    def mount(self):
        if self.mounted or not self.loopdev:
            return self.mounted
        args = [ "/bin/mount", self.loopdev, self.mountdir ]
        if self.fstype:
            args.extend(["-t", self.fstype])
        rc = subprocess.call(args)
        if rc == 0:
            self.mounted = True
        return self.mounted

class SparseExt3LoopbackMount(LoopbackMount):
    def __init__(self, lofile, mountdir, size, fslabel = None):
        LoopbackMount.__init__(self, lofile, mountdir, fstype = "ext3")
        self.size = size
        self.fslabel = fslabel
        if not self.fslabel:
            self.fslabel = "livecd-" + time.strftime("%Y%m%d-%H%M")

    def _createSparseFile(self):
        dir = os.path.dirname(self.lofile)
        if not dir:
            os.makedirs(dir)

        # create the sparse file
        fd = os.open(self.lofile, os.O_WRONLY | os.O_CREAT)
        off = long(self.size * 1024L * 1024L)
        os.lseek(fd, off, 0)
        os.write(fd, '\x00')
        os.close(fd)

    def _formatFilesystem(self):
        rc = subprocess.call(["/sbin/mkfs.ext3", "-F", "-L", self.fslabel,
                              "-m", "1", self.lofile])
        if rc != 0:
            raise OSError, "Error creating filesystem: %d" %(rc,)
        rc = subprocess.call(["/sbin/tune2fs", "-c0", "-i0", "-Odir_index",
                              "-ouser_xattr,acl", self.lofile])

    def setup(self):
        self._createSparseFile()
        self._formatFilesystem()
        return LoopbackMount.setup(self)

class LiveCDYum(yum.YumBase):
    def __init__(self):
        yum.YumBase.__init__(self)

    def doFileLogSetup(self, uid, logfile):
        # don't do the file log for the livecd as it can lead to open fds
        # being left and an inability to clean up after ourself
        pass

    def setup(self, instroot):
        self.installroot = instroot
        self.doConfigSetup(root=instroot, init_plugins = False)
        self.doGenericSetup()

        self.conf.cachedir = "/var/cache/yum"

        # disable the default repos and just enable ours
        map(lambda x: x.disable(), self.repos.listEnabled())

    def reset(self):
        self.closeRpmDB()
        self.doTsSetup()
        self.doRpmDBSetup()

    def selectPackage(self, pkg):
        """Select a given package.  Can be specified with name.arch or name*"""
        try:
            mbrs = self.install(pattern = pkg)
            return len(mbrs)
        except yum.Errors.InstallError:
            print >> sys.stderr, "No package matching %s" %(pkg,)
            return 0
        
    def deselectPackage(self, pkg):
        """Deselect package.  Can be specified as name.arch or name*"""
        sp = pkg.rsplit(".", 2)
        txmbrs = []
        if len(sp) == 2:
            txmbrs = self.tsInfo.matchNaevr(name=sp[0], arch=sp[1])

        if len(txmbrs) == 0:
            exact, match, unmatch = yum.packages.parsePackages(self.pkgSack.returnPackages(), [pkg], casematch=1)
            for p in exact + match:
                txmbrs.append(p)

        if len(txmbrs) > 0:
            map(lambda x: self.tsInfo.remove(x.pkgtup), txmbrs)
        else:
            print >> sys.stderr, "No such package %s to remove" %(pkg,)

    def selectGroup(self, grp, include = GROUP_DEFAULT):
        yum.YumBase.selectGroup(self, grp)
        if include == GROUP_REQUIRED:
            map(lambda p: self.deselectPackage(p), grp.default_packages.keys())
        elif include == GROUP_ALL:
            map(lambda p: self.selectPackage(p), grp.optional_packages.keys())
        
    def addRepository(self, name, url = None, mirrorlist = None):
        repo = yum.yumRepo.YumRepository(name)
        if url:
            repo.baseurl.append(url)
        if mirrorlist:
            repo.mirrorlist = mirrorlist
        conf = yum.config.RepoConf()
        for k, v in conf.iteritems():
            if v or not hasattr(repo, k):
                repo.setAttribute(k, v)
        repo.basecachedir = self.conf.cachedir
        repo.metadata_expire = 0
        # disable gpg check???
        repo.gpgcheck = 0
        repo.enable()
        repo.setup(0)
        self.repos.add(repo)
            
    def runInstall(self):
        (res, resmsg) = self.buildTransaction()
        if res != 2:
            print "Unable to build transaction"
            for m in resmsg:
                print m
            sys.exit(1)
        
        dlpkgs = map(lambda x: x.po, filter(lambda txmbr: txmbr.ts_state in ("i", "u"), self.tsInfo.getMembers()))
        self.downloadPkgs(dlpkgs)
        # FIXME: sigcheck?
        
        self.initActionTs()
        self.populateTs(keepold=0)
        self.ts.check()
        self.ts.order()
        # FIXME: callback should be refactored a little in yum 
        sys.path.append('/usr/share/yum-cli')
        import callback
        cb = callback.RPMInstallCallback()
        cb.tsInfo = self.tsInfo
        cb.filelog = False
        return self.runTransaction(cb)

def touch(fn):
    f = open(fn, "w+")
    f.close()

def get_kernel_version(root):
    # FIXME: this doesn't handle multiple kernels being installed
    kdir = os.listdir("%s/install_root/lib/modules" %(root,))
    kver = os.path.basename(kdir[0])
    return kver

class InstallationTarget:
    def __init__(self):
        self.ayum = LiveCDYum()
        
    def base_on_iso(self, base_on):
        """helper function to extract ext3 file system from a live CD ISO"""

        isoloop = LoopbackMount(base_on, "%s/base_on_iso" %(self.build_dir,))
        if not isoloop.setup():
            isoloop.cleanup()
            return False

        squashloop = LoopbackMount("%s/squashfs.img" %(isoloop.mountdir,),
                                   "%s/base_on_squashfs" %(self.build_dir,),
                                   "squashfs")
        if not squashloop.setup():
            squashloop.cleanup()
            isoloop.cleanup()
            return False

        # copy the ext3 fs out
        try:
            shutil.copyfile("%s/base_on_squashfs/os.img" %(self.build_dir,),
                            "%s/data/os.img" %(self.build_dir,))
        except Exception, e:
            print "Cannot copy os.img from squashfs from ISO to base on"
            traceback.print_exc(file=sys.stderr)
            squashloop.cleanup()
            isoloop.cleanup()
            return False

        # unmount and tear down the mount points and loop devices used
        squashloop.cleanup()
        isoloop.cleanup()
        return True


    def setup(self, image_size, fs_label, base_on):
        """setup target ext3 file system in preparation for an install"""

        # global variables needed
        self.fs_label = fs_label
        self.instloop = None
        self.bindmounts = []

        # setup temporary build dirs
        self.build_dir = "/var/tmp/livecd-creator/build-" + os.path.basename(tempfile.mktemp())
        try:
            os.makedirs(self.build_dir)
        except OSError:
            print "Cannot create build directory at %s" %(self.build_dir,)
            return False

        try:
            os.mkdir(self.build_dir + "/out")
            os.mkdir(self.build_dir + "/out/isolinux")
            os.mkdir(self.build_dir + "/out/sysroot")
            os.mkdir(self.build_dir + "/data")
            os.mkdir(self.build_dir + "/data/sysroot")
            os.mkdir(self.build_dir + "/install_root")
            os.mkdir(self.build_dir + "/yum-cache")
        except OSError:
            print "Cannot create directory"
            self.teardown()
            return False

        if base_on:
            # get backing ext3 image if we're based this build on an existing live CD ISO
            if not self.base_on_iso(base_on):
                self.teardown()
                return False
            self.instloop = LoopbackMount("%s/data/os.img" %(self.build_dir,),
                                          "%s/install_root" %(self.build_dir,))
        else:
            self.instloop = SparseExt3LoopbackMount("%s/data/os.img"
                                                    %(self.build_dir,),
                                                    "%s/install_root"
                                                    %(self.build_dir,),
                                                    image_size)
            

        if not self.instloop.setup():
            self.teardown()
            return False

        if not base_on:
            # create a few directories needed if it's a new image
            try:
                os.mkdir(self.build_dir + "/install_root/etc")
                os.mkdir(self.build_dir + "/install_root/boot")
                os.mkdir(self.build_dir + "/install_root/var")
                os.mkdir(self.build_dir + "/install_root/var/log")
                os.mkdir(self.build_dir + "/install_root/var/cache")
                os.mkdir(self.build_dir + "/install_root/var/cache/yum")
            except OSError:
                print "Cannot create directory"
                self.teardown()
                return False

        # bind mount system directories into install_root/
        for f in ["/sys", "/proc", "/dev", "/dev/pts", "/selinux"]:
            b = BindChrootMount(f, "%s/install_root" %(self.build_dir,))
            if b.mount():
                self.bindmounts.append(b)
            else:
                print "Cannot mount special file system %s"%f
                self.teardown()
                return False

        # make sure /etc/mtab is current inside install_root
        try:
            os.symlink("../proc/mounts", self.build_dir + "/install_root/etc/mtab")
        except OSError:
            print "Cannot create symlink %s/etc/mtab -> ../proc/mounts"%(self.build_dir)
            self.teardown()
            return False

        # write an /etc/fstab file
        fstab = open(self.build_dir + "/install_root/etc/fstab", "w")
        fstab.write("/dev/mapper/livecd-rw   /                       ext3    defaults,noatime 0 0\n")
        fstab.write("devpts                  /dev/pts                devpts  gid=5,mode=620  0 0\n")
        fstab.write("tmpfs                   /dev/shm                tmpfs   defaults        0 0\n")
        fstab.write("proc                    /proc                   proc    defaults        0 0\n")
        fstab.write("sysfs                   /sys                    sysfs   defaults        0 0\n")
        fstab.close()

        b = BindChrootMount("%s/yum-cache" %(self.build_dir,),
                            "%s/install_root" %(self.build_dir,),
                            "/var/cache/yum")
        if b.mount():
            self.bindmounts.append(b)
        else:
            print "Cannot bind mount /var/cache/yum"
            self.teardown()
            return False

        self.ayum.setup("%s/install_root" %(self.build_dir,))
        return True


    def unmount(self):
        """detaches system bind mounts and install_root for the file system and tears down loop devices used"""
        
        try:
            os.unlink(self.build_dir + "/install_root/etc/mtab")
        except OSError:
            pass

        # TODO: need to handle when unmount fails because of lingering
        # processes that has open files
        if self.instloop:
            self.bindmounts.reverse()
            for b in self.bindmounts:
                b.umount()
            self.instloop.cleanup()
            try:
                os.unlink(self.build_dir + "/yum.conf")
            except OSError:
                pass
            shutil.rmtree("%s/yum-cache" %(self.build_dir,), ignore_errors=True)

            self.instloop = None

    def teardown(self):
        """releases all resources and removes all temporary files"""

        # ensure we've detached the install_root
        self.unmount()

        # this removes all data used in the temporary build directory
        try:
            os.unlink(self.build_dir + "/data/os.img")
            os.rmdir(self.build_dir + "/data")
        except OSError:
            pass
        shutil.rmtree("%s/out" %(self.build_dir,), ignore_errors=True)
        if "/var/tmp/livecd-creator/build-" in self.build_dir:
            shutil.rmtree(self.build_dir, ignore_errors=True)

    def addRepository(self, name, url):
        """adds a yum repository to temporary yum.conf file used"""
        self.ayum.addRepository(name, url)

    def run_in_root(self):
        os.chroot("%s/install_root" %(self.build_dir,))

    def installPackages(self, packageList, excludePackageList, groupList = []):
        """install packages into target file system"""
        map(lambda pkg: self.ayum.selectPackage(pkg), packageList)
        for (grp, inc) in groupList:
            self.ayum.selectGroup(grp, inc)
        map(lambda pkg: self.ayum.deselectPackage(pkg), excludePackageList)

        try:
            self.ayum.runInstall()
        except Exception, e:
            print "Error installing packages"
            traceback.print_exc(file=sys.stderr)            
            return False
        self.ayum.closeRpmDB()
        return True

    def configureSystem(self, ksparser):
        instroot = "%s/install_root" %(self.build_dir,)
        
        # FIXME: this is a bit ugly, but with the current pykickstart
        # API, we don't really have a lot of choice.  it'd be nice to
        # be able to do something different, but so it goes

        # set up the language
        lang = ksparser.handler.lang.lang or "en_US.UTF-8"
        f = open("%s/etc/sysconfig/i18n" %(instroot,), "w+")
        f.write("LANG=\"%s\"\n" %(lang,))
        f.close()

        # next, the keyboard
        # FIXME: should this impact the X keyboard config too???
        # or do we want to make X be able to do this mapping
        import rhpl.keyboard
        k = rhpl.keyboard.Keyboard()
        if ksparser.handler.keyboard.keyboard:
            k.set(ksparser.handler.keyboard.keyboard)
        k.write(instroot)

        # next up is timezone
        tz = ksparser.handler.timezone.timezone or "America/New_York"
        utc = ksparser.handler.timezone.isUtc
        f = open("%s/etc/sysconfig/clock" %(instroot,), "w+")
        f.write("ZONE=\"%s\"\n" %(tz,))
        f.write("UTC=%s\n" %(utc,))
        f.close()

        # FIXME: we should handle network bits better
        f = open("%s/etc/sysconfig/network" %(instroot,), "w+")
        f.write("NETWORKING=yes\n")
        f.write("HOSTNAME=localhost.localdomain\n")
        f.close()
        f = open("/%s/etc/hosts" %(instroot,), "w+")
        f.write("127.0.0.1\t\tlocalhost.localdomain  localhost\n")
        f.write("::1\t\tlocalhost6.localdomain6 localhost6\n")        
        f.close()

        # do any authconfig bits
        auth = ksparser.handler.authconfig.authconfig or "--useshadow --enablemd5"
        if os.path.exists("%s/usr/sbin/authconfig" %(instroot,)):
            args = ["/usr/sbin/authconfig", "--update", "--nostart"]
            args.extend(auth.split())
            subprocess.call(args, preexec_fn=self.run_in_root)

        # firewall.  FIXME: should handle the rest of the options
        if ksparser.handler.firewall.enabled and os.path.exists("%s/usr/sbin/lokkit" %(instroot,)):
            subprocess.call(["/usr/sbin/lokkit", "-f", "--quiet",
                             "--nostart", "--enabled"],
                            preexec_fn=self.run_in_root)

        # selinux
        if os.path.exists("%s/usr/sbin/lokkit" %(instroot,)):
            args = ["/usr/sbin/lokkit", "-f", "--quiet", "--nostart"]
            if ksparser.handler.selinux.selinux:
                args.append("--selinux=enforcing")
            else:
                args.append("--selinux=disabled")
            subprocess.call(args, preexec_fn=self.run_in_root)

        # FIXME: we should allow the setting of the root pass
        subprocess.call(["passwd", "-d", "root"], preexec_fn=self.run_in_root)

        # enable/disable services appropriately
        for s in ksparser.handler.services.enabled:
            subprocess.call(["/sbin/chkconfig", s, "--level", "345", "on"],
                            preexec_fn=self.run_in_root)
        for s in ksparser.handler.services.disabled:
            subprocess.call(["/sbin/chkconfig", s, "--level", "345", "off"],
                            preexec_fn=self.run_in_root)

        # x by default?
        if ksparser.handler.xconfig.startX:
            f = open("%s/etc/inittab" %(instroot,), "rw+")
            buf = f.read()
            buf = buf.replace("id:3:initdefault", "id:5:initdefault")
            f.seek(0)
            f.write(buf)
            f.close()

        # and now, for arbitrary %post scripts
        for s in filter(lambda s: s.type == KS_SCRIPT_POST,
                        ksparser.handler.scripts):
            # we can only safely run scripts in the chroot
            if not s.inChroot:
                print >> sys.stderr, "Not running script outside of chroot"
                continue

            (fd, path) = tempfile.mkstemp("", "ks-script-", "%s/tmp" %(instroot,))
            os.write(fd, s.script)
            os.close(fd)
            os.chmod(path, 0700)

            subprocess.call([s.interp, "/tmp/%s" %(os.path.basename(path),)],
                            preexec_fn = self.run_in_root)
            

    def createInitramfs(self):
        # Create initramfs
        shutil.copy("/usr/lib/livecd-creator/mayflower",
                        "%s/install_root/sbin/mayflower" %(self.build_dir,))
        shutil.copy("/usr/lib/livecd-creator/run-init",
                        "%s/install_root/sbin/run-init" %(self.build_dir,))
        # modules needed for booting (this is butt ugly and we need to retrieve this from elsewhere, e.g. the kernel)
        mayflowerconf = open(self.build_dir + "/install_root/etc/mayflower.conf", "w")
        mayflowerconf.write('MODULES+="cdrom ide-cd ahci loop dm_snapshot squashfs ext3 ehci_hcd uhci_hcd ohci_hcd usb_storage sd_mod sr_mod usbhid ata_piix "\n')
        mayflowerconf.write('MODULES+="sata_mv sata_qstor sata_sis sata_uli "\n')
        mayflowerconf.write('MODULES+="sata_nv sata_sil24 sata_svw sata_via "\n')
        mayflowerconf.write('MODULES+="sata_promise sata_sil sata_sx4 sata_vsc "\n')
        mayflowerconf.write('MODULES+="ata_generic pata_ali pata_amd pata_artop pata_atiixp pata_cmd64x pata_cs5520 pata_cs5530 pata_cs5535 pata_cypress pata_efar pata_hpt366 pata_hpt37x pata_hpt3x2n pata_hpt3x3 pata_isapnp pata_it821x pata_jmicron pata_marvell pata_mpiix pata_netcell pata_ns87410 pata_oldpiix pata_optidma pata_opti pata_pcmcia pata_pdc2027x pata_pdc202xx_old pata_qdi pata_serverworks pata_sil680 pata_sis pata_sl82c105 pata_triflex pata_via pdc_adma "\n')        
        mayflowerconf.close()

        subprocess.call(["/sbin/mayflower", "-f", "/boot/livecd-initramfs.img",
                         get_kernel_version(self.build_dir)],
                        preexec_fn=self.run_in_root)
        for f in ("/sbin/mayflower", "/sbin/run-init", "/etc/mayflower.conf"):
            os.unlink("%s/install_root/%s" %(self.build_dir, f))

    def relabelSystem(self):
        # finally relabel all files
        subprocess.call(["/sbin/fixfiles", "restore", "/"],
                        preexec_fn=self.run_in_root)
        return True

    def configureBootloader(self):
        """configure the boot loader"""
        
        # set up boot loader
        #
        # TODO:
        #  - fix for archs not using grub
        #  - fix for non-i386
        #  - error handling
        #
        shutil.copyfile("%s/install_root/boot/vmlinuz-%s"
                        %(self.build_dir, get_kernel_version(self.build_dir,)),
                        "%s/out/isolinux/vmlinuz" %(self.build_dir,))

        shutil.copyfile("%s/install_root/boot/livecd-initramfs.img"
                        %(self.build_dir,),
                        "%s/out/isolinux/initrd.img" %(self.build_dir,))
        os.unlink("%s/install_root/boot/livecd-initramfs.img"
                  %(self.build_dir,))

        shutil.copy("%s/install_root/usr/lib/syslinux/isolinux.bin" %(self.build_dir,),
                    "%s/out/isolinux/isolinux.bin" %(self.build_dir,))
        shutil.copy("%s/install_root/usr/lib/syslinux/vesamenu.c32" %(self.build_dir,),
                    "%s/out/isolinux/vesamenu.c32" %(self.build_dir,))
        shutil.copy("%s/install_root/usr/lib/anaconda-runtime/syslinux-vesa-splash.jpg" %(self.build_dir,),
                    "%s/out/isolinux/splash.jpg" %(self.build_dir,))

        cfg = """
default vesamenu.c32
timeout 600

menu background splash.jpg
menu title Welcome to Fedora!
menu color border 0 #ffffffff #00000000
menu color sel 0 #ffffffff #ff000000
menu color title 0 #ffffffff #00000000
menu color tabmsg 0 #ffffffff #00000000
menu color unsel 0 #ffffffff #00000000
menu color hotsel 0 #ff000000 #ffffffff
menu color hotkey 0 #ffffffff #ff000000

label linux
  menu label %(label)s
  kernel vmlinuz
  append initrd=initrd.img  ro quiet root=CDLABEL=%(label)s rootfstype=iso9660 livecd

label runfromram
  menu label %(label)s from RAM
  kernel vmlinuz
  append initrd=initrd.img ro quiet root=CDLABEL=%(label)s rootfstype=iso9660 livecd livecd_ram
""" %{"label": self.fs_label}

        cfgf = open("%s/out/isolinux/isolinux.cfg" %(self.build_dir,), "w")
        cfgf.write(cfg)
        cfgf.close()
        
        # TODO: enable external entitity to partipate in adding boot entries

    def createIso(self, filename):
        """write out the live CD ISO"""
        subprocess.call(["/usr/bin/mkisofs", "-o", "%s.iso" %(filename,),
                         "-b", "isolinux/isolinux.bin",
                         "-c", "isolinux/boot.cat",
                         "-no-emul-boot", "-boot-load-size", "4",
                         "-boot-info-table", "-J", "-r", "-hide-rr-moved",
                         "-V", "%s" %(filename,), "%s/out" %(self.build_dir)])

    def createSquashFS(self):
        """create compressed squashfs file system"""
        # FIXME: mksquashfs segfaults if PWD isn't set in the environment
        subprocess.call(["/sbin/mksquashfs", "os.img", "sysroot",
                         "../out/squashfs.img"],
                        cwd="%s/data" %(self.build_dir,),
                        env={"PWD": "%s/data" %(self.build_dir,)})

def usage():
    print "usage: livecd-creator [--help] "
    print "                      [--config=<path-to-kickstart-file>]"
    print "                      [--repo=<name1>,<url1> ...] [--repo=<name2>,<url2>]"
    print "                      --package=<p1> [--package=<p2> ...]"
    print "                      [--exclude-package=<e1>] --exclude-package=<e2> ...]"
    print "                      [--base-on=<path-to-iso-file>]"
    print "                      [--fslabel=<label>]"
    print ""
    print " --help             : Print usage and exit"
    print " --config           : Path to kickstart config file"
    print " --repo             : Path to yum repository"
    print " --package          : Include this package"
    print " --exclude-package  : Exclude this package"
    print " --base-on          : Add packages to an existing live CD iso9660 image"
    print " --fslabel          : File system label (default: livecd-YYYYMMDD-HHMI)"
    print ""

def main():

    repos = []
    packages = []
    groups = []
    epackages = []
    fs_label = "livecd-" + time.strftime("%Y%m%d-%H%M")
    base_on = None
    kscfg = None

    try:
        opts, args = getopt.getopt(sys.argv[1:], "hr:b:p:e:f:c:",
                                   ["help", "repo=", "base-on=", "package=", "exclude-package=", "fslabel=", "config="])
    except getopt.GetoptError:
        usage()
        sys.exit(2)
    output = None
    verbose = False
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit(0)
        if o in ("-c", "--config"):
            kscfg = a
            continue
        if o in ("-r", "--repo"):
            (name, url) = a.split(",")
            for (n, u) in repos:
                if n == name:
                    print "Repo name '%s' is already in use"%n
                    sys.exit(2)
            repos.append((name, url))
            continue
        if o in ("-p", "--package"):
            if a.startswith("@"):
                groups.append((a[1:], GROUP_DEFAULT))
            else:
                packages.append(a)
            continue
        if o in ("-e", "--exclude-package"):
            epackages.append(a)
            continue
        if o in ("-f", "--fslabel"):
            fs_label = a
            if len(fs_label) > 32:
                print "CD labels are limited to 32 characters"
                sys.exit(2)
            continue
        if o in ("-b", "--base-on"):
            base_on = a
            continue
        print "Unknown option %s"%o
        sys.exit(2)

    ksparser = KickstartParser(makeVersion())
    if not kscfg:
        if len(packages) == 0:
            print "No packages specified."
            print ""
            usage()
            sys.exit(1)

        if len(repos) == 0:
            print "No repositories specified."
            print ""
            usage()
            sys.exit(1)
    else:
        ksparser.readKickstart(kscfg)

        for repo in ksparser.handler.repo.repoList:
            repos.append( (repo.name, repo.baseurl) )

        packages.extend(ksparser.handler.packages.packageList)
        groups.extend(map(lambda g: (g.name, g.include),
                          ksparser.handler.packages.groupList))
        epackages.extend(ksparser.handler.packages.excludedList)

    target = InstallationTarget()

    if not target.setup(3*1024, fs_label, base_on):
        print "Cannot setup installation target. Aborting."
        sys.exit(1)

    try:
        for (n, u) in repos:
            target.addRepository(n, u)

        if not target.installPackages(packages, epackages, groups):
            target.teardown()
            sys.exit(1)
        target.configureSystem(ksparser)
        target.createInitramfs()
        if ksparser.handler.selinux.selinux:
            target.relabelSystem()
        target.configureBootloader()
    except:
        print "\n\nERROR during installation..."
        traceback.print_exc(file=sys.stderr)
        target.teardown()
        sys.exit(1)

    #os.system("/bin/bash")

    target.unmount()
    target.createSquashFS()
    target.createIso(fs_label)
    target.teardown()

if __name__ == "__main__":
    main()
