#!/usr/bin/python
#
# livecd-creator : Creates Live CD based for Fedora.
#
# Copyright 2007, Red Hat  Inc.
# Copyright 2016, Kevin Kofler
# Copyright 2016, Neal Gompa
# Copyright 2023, Fedora Project
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import os
import os.path
import sys
import time
import optparse
import logging
from dnf.exceptions import Error as DnfBaseError

import imgcreate
from imgcreate.errors import KickstartError

class Usage(Exception):
    def __init__(self, msg = None, no_error = False):
        Exception.__init__(self, msg, no_error)

def parse_options(args):
    parser = optparse.OptionParser()

    imgopt = optparse.OptionGroup(parser, "Image options",
                                  "These options define the created image.")
    imgopt.add_option("-c", "--config", type="string", dest="kscfg",
                      help="Path or url to kickstart config file")
    imgopt.add_option("-b", "--base-on", type="string", dest="base_on",
                      help="Add packages to an existing live CD iso9660 image.")
    imgopt.add_option("-f", "--fslabel", type="string", dest="fslabel",
                      help="File system label (default based on config name)")
    # Provided for imgcreate compatibility
    imgopt.add_option("-n", "--name", type="string", dest="fslabel",
                      help=optparse.SUPPRESS_HELP)
    imgopt.add_option("", "--title", type="string", dest="title",
                      help="Title used in syslinux.cfg file"),
    imgopt.add_option("", "--product", type="string", dest="product",
                      help="Product name used in boot configurationstanzas and "
                           "countdown."),
    imgopt.add_option("", "--releasever", type="string", dest="releasever",
                      default=None,
                      help="Value to substitute for $releasever in kickstart repo urls")
    imgopt.add_option("", "--syslinux", action="store_true",
                      dest="syslinux", default=False,
                      help="Use SYSLINUX for BIOS booting.")
    imgopt.add_option("", "--nomacboot", action="store_true",
                      dest="nomacboot", default=False,
                      help="Do not create HFS+ boot image or partition.")
    imgopt.add_option("", "--flat-squashfs", action="store_true",
                      dest="flat_squashfs",
                      help="Specify squashing the root filesystem directly. "
                           "This eliminates the intermediate LiveOS directory "
                           "holding another filesystem image file.  This is "
                           "suitable only for OverlayFS overlays.",
                      default=False)
    imgopt.add_option("", "--compression-type", type="string", dest="compress_args",
                      metavar='"TYPE ARG1 ARG2 ..."',
                      help="Compression type recognized by mksquashfs. "
                           "(The default, xz, needs a 2.6.38+ kernel; gzip works "
                           "with all kernels; lzo needs a 2.6.36+ kernel; lz4 "
                           "needs a 3.19+ kernel; lzma needs custom kernel.) "
                           'xz1m is interpreted as "xz -b 1M -Xdict-size 1M -norecovery". '
                           "Set to 'None' to cause the program to read the compression "
                           "type from the base_on image. "
                           "Multiple arguments should be specified in "
                           'one string, i.e., --compression-type "type arg1 arg2 ...".',
                      default="xz")
    imgopt.add_option("", "--dracut-args", type="string",
                      dest="dracut_args", default="", metavar='"[+]ARG0 ARG1 ..."',
                      help="The arguments to be used by dracut to configure "
                           "the initrd. Saved at /etc/dracut.conf.d/99-liveos.conf. "
                           "This file persists only for the life of the install_root "
                           "mount.  (A future version of dracut will save this file "
                           "in the initrd under /usr/lib/dracut/conffiles/ or another "
                           "regular path.)  Each argument consists of an attribute and "
                           "a value (see dracut.conf.5). If the first argument string is "
                           "prefixed with a '+' character, the additional arguments will "
                           "be appended to the default set (superseding any there):\n "
                           "mdadmconf=no "
                           "lvmconf=no "
                           "compress=xz "
                           "add_dracutmodules+=\" livenet dmsquash-live dmsquash-live-ntfs convertfs pollcdrom qemu qemu-net \" "
                           "omit_dracutmodules+=\" plymouth \" "
                           "hostonly=no "
                           "early_microcode=no ")
    imgopt.add_option("-p", "--plugins", action="store_true", dest="plugins",
                      help="Use DNF plugins during image creation",
                      default=False)
    imgopt.add_option("", "--image-type", type="string", dest="image_type",
                      help=optparse.SUPPRESS_HELP)
    imgopt.add_option("", "--repo", type="string", dest="repo",
                      default=None,
                      help="Configure RPM repositories from a .repo file or directory "
                           "instead of kickstart. See /etc/yum.repos.d/ for example "
                           "configuration files.")
    imgopt.add_option("", "--pkgverify-level",
                      type="choice",
                      choices=["all", "signature", "digest", "none"],
                      dest="pkgverify_level",
                      default=None,
                      help="Configures RPM package verification. Use \"all\" to enforce "
                           "trusted GPG signatures and strong digests for every "
                           "package. Only affects packages installed during the "
                           "%install step.")
    parser.add_option_group(imgopt)

    # options related to the config of your system
    sysopt = optparse.OptionGroup(parser, "System directory options",
            "These options define directories used on your system for creating the live image")
    sysopt.add_option("-t", "--tmpdir", type="string",
                      dest="tmpdir", default="/var/tmp",
                      help="Temporary directory to use (default: /var/tmp)")
    sysopt.add_option("-o", "--output", type="string",
                      dest="destdir", default=".",
                      help="The directory path where the image .iso will be saved (default: '.')")
    sysopt.add_option("", "--cache", type="string",
                      dest="cachedir", default=None,
                      help="Cache directory to use (default: private cache")
    sysopt.add_option("", "--cacheonly", action="store_true",
                      dest="cacheonly", default=False,
                      help="Work offline from cache, use together with --cache (default: False)")
    # Start a shell in the chroot for post-configuration.
    sysopt.add_option("-l", "--shell", action="store_true", dest="give_shell",
                      help="Launch a change root shell in the installation "
                           "root filesystem. This includes bind mounts to the host "
                           "directories /dev, /dev/pts, /dev/shm, /proc, /sys, "
                           "/sys/fs/selinux, the creator iso directory (mounted at "
                           "/run/iso), and the host root filesystem (mounted at "
                           "/run/hostroot).")
    sysopt.add_option("", "--nocleanup", action="store_true",
                      dest="nocleanup", default=False,
                      help="Skip cleanup of temporary files")
    parser.add_option_group(sysopt)

    imgcreate.setup_logging(parser)

    # debug options not recommended for "production" images
    # Don't compress the image.
    parser.add_option("-s", "--skip-compression", action="store_true", dest="skip_compression",
                      help=optparse.SUPPRESS_HELP)
    parser.add_option("", "--skip-minimize", action="store_true", dest="skip_minimize",
                      help=optparse.SUPPRESS_HELP)

    (options, args) = parser.parse_args()

    # Pretend to be a image-creator if called with that name
    if not options.image_type:
        if sys.argv[0].endswith('image-creator'):
            options.image_type = 'image'
        else:
            options.image_type = 'livecd'
    if options.image_type not in ('livecd', 'image'):
        raise Usage("'%s' is not a recognized image type" % options.image_type)

    # image-create compatibility: Last argument is kickstart file
    if len(args) == 1:
        options.kscfg = args.pop()
    if len(args):
        raise Usage("Extra arguments given")

    if not options.kscfg:
        raise Usage("Kickstart file must be provided")
    if not os.path.exists(options.kscfg):
        raise Usage("Kickstart file '%s' does not exist" % (options.kscfg))
    if options.base_on and not os.path.isfile(options.base_on):
        raise Usage("Image file '%s' does not exist" %(options.base_on,))
    if options.image_type == 'livecd':
        if options.fslabel and len(options.fslabel) > imgcreate.FSLABEL_MAXLEN:
            raise Usage("CD labels are limited to 32 characters")
        if options.fslabel and options.fslabel.find(" ") != -1:
            raise Usage("CD labels cannot contain spaces.")

    return options

def main():
    try:
        options = parse_options(sys.argv[1:])
    except Usage as livecd_creator_optparse_except:
        (msg, no_error) = livecd_creator_optparse_except.args
        if no_error:
            out = sys.stdout
            ret = 0
        else:
            out = sys.stderr
            ret = 2
        if msg:
            print(msg, file=out)
        return ret

    if os.geteuid () != 0:
        print("You must run %s as root" % sys.argv[0], file=sys.stderr)
        return 1

    if options.fslabel:
        fslabel = options.fslabel
        name = fslabel
    else:
        name = imgcreate.build_name(options.kscfg, options.image_type + "-")

        fslabel = imgcreate.build_name(options.kscfg,
                                        options.image_type + "-",
                                        maxlen = imgcreate.FSLABEL_MAXLEN,
                                        suffix = "%s-%s" %(os.uname()[4], time.strftime("%Y%m%d%H%M")))

        logging.info("Using label '%s' and name '%s'" % (fslabel, name))

    if options.title:
        title = options.title
    else:
        try:
            title = " ".join(name.split("-")[:2])
            title = title.title()
        except:
            title = "Linux"
    if options.product:
        product = options.product
    else:
        try:
            product = " ".join(name.split("-")[:2])
            product = product.title()
        except:
            product = "Linux"
    logging.info("Using title '%s' and product '%s'" % (title, product))

    try:
        ks = imgcreate.read_kickstart(options.kscfg)
    except KickstartError as e:
        logging.error("kickstart error: %s", e)
        return 1

    if not ks.handler.repo.seen and not options.repo:
        print("Kickstart (%s) must have at least one repository." % (options.kscfg), file=sys.stderr)
        return 1

    if ks.handler.repo.seen and options.repo:
        print("Ignoring kickstart (%s) repo definitions in favor of \"%s\"" %
              (options.kscfg, options.repo), file=sys.stderr)

    if options.pkgverify_level in ("all", "signature") and not options.repo:
        print(f"Option --pkgverify-level={options.pkgverify_level} requires "
              "the use of --repo=PATH for repo configuration",
              file=sys.stderr)
        return 1

    try:
        if options.image_type == 'livecd':
            creator = imgcreate.LiveImageCreator(ks, name,
                                            fslabel=fslabel,
                                            releasever=options.releasever,
                                            tmpdir=os.path.abspath(options.tmpdir),
                                            useplugins=options.plugins,
                                            title=title, product=product,
                                            cacheonly=options.cacheonly,
                                            docleanup=not options.nocleanup)
        elif options.image_type == 'image':
            creator = imgcreate.LoopImageCreator(ks, name,
                                            fslabel=fslabel,
                                            releasever=options.releasever,
                                            useplugins=options.plugins,
                                            tmpdir=os.path.abspath(options.tmpdir),
                                            cacheonly=options.cacheonly,
                                            docleanup=not options.nocleanup)
    except imgcreate.CreatorError as e:
        logging.error(u"%s creation failed: %s", options.image_type, e)
        return 1

    if options.syslinux:
        creator.BIOSbooter = 'SYSLINUX'
    else:
        creator.BIOSbooter = 'GRUB'

    creator.dracut_args = options.dracut_args
    creator.flat_squashfs = options.flat_squashfs
    creator.compress_args = options.compress_args
    creator.skip_compression = options.skip_compression
    creator.skip_hfs = options.nomacboot
    creator.skip_minimize = options.skip_minimize
    if options.cachedir:
        options.cachedir = os.path.abspath(options.cachedir)

    try:
        creator.mount(options.base_on, options.cachedir)
        creator.install({}, options.repo, options.pkgverify_level)
        creator.configure()
        if options.give_shell:
            creator._ImageCreator__load_selinuxfs()
            bindmounts = [('/dev', None), ('/run', None),
                          ('/etc/resolv.conf', None),
                          (creator._LiveImageCreatorBase__isodir, '/run/iso'),
                          ('/', '/run/hostroot')]
            for (f, dest) in bindmounts:
                if os.path.exists(f):
                    creator._ImageCreator__bindmounts.extend(
                    [imgcreate.fs.BindChrootMount(f, creator._instroot, dest)])
                else:
                    logging.warning("Skipping (%s, %s) because source doesn't "
                                 "exist." % (f, dest))
            creator._do_bindmounts()
            print("Launching shell. Exit (Ctrl D) to continue.")
            print("-------------------------------------------")
            creator.launch_shell(PS1='[\\u@\\H:install_root\\w:]\\n\\$ ')
            creator._ImageCreator__destroy_selinuxfs()
            imgcreate.ImageCreator._undo_bindmounts(creator)
            imgcreate.kickstart.SelinuxConfig(creator._instroot).apply(creator.ks.handler.selinux)
        creator.unmount()
        ops = []
        if options.flat_squashfs:
            ops += ['flatten-squashfs']
        creator.package(options.destdir, ops=ops)
    except (imgcreate.CreatorError, DnfBaseError) as e:
        logging.error(u"Error creating Live CD : %s" % e)
        return 1
    finally:
        creator.cleanup()

    return 0

def do_nss_libs_hack():
    import ctypes as forgettable
    hack = forgettable._dlopen('libnss_sss.so.2')
    hack = [ hack, forgettable._dlopen('libnss_systemd.so.2') ]
    del forgettable
    return hack

if __name__ == "__main__":
    hack = do_nss_libs_hack()
    sys.exit(main())
