=pod

=head1 NAME

livecd-creator - creates live CD or DVD images.

=head1 SYNOPSIS

B<livecd-creator> [OPTIONS]

=head1 DESCRIPTION

B<livecd-creator> creates live CD or DVD images(ISO images) from kickstart files. Kickstart files contain information about packages and configuration settings which are used to build the image.

=head1 OPTIONS

=over 4

=item -h, --help

Shows the help message and exits.

=back

=head1 IMAGE OPTIONS

These options define the created image.

=over 4

=item -c KSCFG, --config=KSCFG

Path to kickstart configuration file.

=item -b BASE_ON, --base-on=BASE_ON

Add packages to an existing live CD iso9660 image.

=item -f FS_LABEL, --fslabel=FS_LABEL

Defines the file system label. The default is based on the configuration name.

=item --title=TITLE

Title used by syslinux.cfg file

=item --product=PRODUCT

Product name used in syslinux.cfg boot stanzas and countdown

=item  -p, --plugins

Use DNF plugins during image creation

=item --compression-type=COMPRESSOR

Specify a compressor recognized by mksquashfs.
xz is the default and works with 2.6.38 and later kernels.
gzip works with all kernels.
lzo works with 2.6.36 and later kernels.
lzma will only work with custom kernels.
Set to 'None' to force reading the compressor used in BASE_ON.
If gzip is used, the -comp option is not passed to mksquashfs to allow the use of older versions of mksquashfs.

=item --releasever=VER

Set the value to substitute for $releasever in kickstart repo urls

=back

=head1 SYSTEM DIRECTORY OPTIONS

These options define directories used on your system for creating the live image.

=over 4

=item -t TMPDIR, --tmpdir=TMPDIR

defines the temporary directory to use. The default directory is /var/tmp.

=item --cache=CACHEDIR

Defines the cache directory to use (default: private cache).

=item --cacheonly

Work offline from cache, use together with --cache (default: False)

=item --nocleanup

Skip cleanup of temporary files

=back

=head1 DEBUGGING OPTIONS

These options control the output of logging information during image creation

=over 4

=item -d, --debug

Output debugging information

=item -v, --verbose

Output verbose progress information

=item -q, --quiet

Supress stdout

=item --logfile=FILE

Save debug information to FILE

=back

=head1 EXAMPLES

Barebones LiveCD

livecd-creator \
--config=/usr/share/livecd-tools/livecd-fedora-minimal.ks

Fedora Desktop Live CD

livecd-creator \
--config=/usr/share/livecd-tools/livecd-fedora-desktop.ks \
--fslabel=Fedora9-LiveCD-foo

=head1 REPO EXTENSIONS

livecd-creator provides for some extensions to the repo commands similar
to what DNF supports. The strings $arch, $basearch and $releasever
are replaced with the system arch, basearch and release version respectively.
When no --releasever is passed it defaults to the current system's version.
The allows the use of repo commands such as the following:

repo --name=fedora --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-$releasever&arch=$basearch

Note that in a chroot environment (like koji) the rpmdb is not available,
so either don't use $releasever in that case, or pass --releasever=VER

=head1 CONTRIBUTORS

David Zeuthen, Jeremy Katz, Douglas McClendon and a team of many other contributors. See the AUTHORS file in the source distribution for the complete list of credits. 

=head1 BUGS

Report bugs to the mailing list C<http://www.redhat.com/mailman/listinfo/fedora-livecd-list> or directly to Bugzilla C<http://bugzilla.redhat.com/bugzilla/> against the C<Fedora> product, and the C<livecd-tools> component.

=head1 COPYRIGHT

Copyright (C) Fedora Project 2008,2009, and various contributors. This is free software. You may redistribute copies of it under the terms of the GNU General Public License C<http://www.gnu.org/licenses/gpl.html>. There is NO WARRANTY, to the extent permitted by law.

=head1 SEE ALSO

C<livecd-iso-to-disk(1)>, project website C<http://fedoraproject.org/wiki/FedoraLiveCD>

=cut
