#!/bin/sh
#
# livecd-install-daemon:   Live CD Installer
#
# chkconfig: 345 99 01
# description:  This is a daemon for live CD installs. This init script
#               will go away once D-Bus system bus activation is merged.
#               See http://fedoraproject.org/wiki/FedoraLiveCD
#
# processname: livecd-installer
#

# Sanity checks.
[ -x /usr/libexec/livecd-installer ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

# so we can rearrange this easily
processname=livecd-installer
servicename=livecd-install-daemon
pidfile=/var/run/livecd-installer.pid

RETVAL=0

start() {
    echo -n $"Starting live CD installer daemon: "
    # nasty hack, but this is temporary...
    /usr/libexec/$processname &
    success
    echo
}

stop() {
    echo -n $"Stopping live CD installer daemon: "
    killall livecd-installer
    success
    echo
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        ;;
esac
exit $RETVAL
